org: brandonbr1208
app: my-app
service: users-api-java

provider:
  name: aws
  runtime: java21
  stage: dev
  region: us-east-1
  memorySize: 512
  timeout: 15
  deploymentMethod: direct
  environment:
    TABLE_NAME: users
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - arn:aws:dynamodb:us-east-1:*:table/users

package:
  artifact: build/libs/users-api-java-1.2.0.jar

functions:
  getUsers:
    handler: com.pragma.handler.HandlerGet
    events:
      - httpApi:
          path: /user/list
          method: GET

  createUser:
    handler: com.pragma.handler.HandlerCreate
    events:
      - httpApi:
          path: /user/create
          method: POST

  updateUser:
    handler: com.pragma.handler.HandlerUpdate
    events:
      - httpApi:
          path: /user/{id}
          method: PUT

  deleteUser:
    handler: com.pragma.handler.HandlerDelete
    events:
      - httpApi:
          path: /user/{id}
          method: DELETE