AWSTemplateFormatVersion: '2010-09-09'
Description: Infraestructura base con API Gateway y Lambdas

Parameters:
  Stage:
    Type: String
    Default: dev
    Description: Etapa de despliegue

Resources:
  # ----------------------------------------------------
  # 1. API GATEWAY (HTTP API)
  # ----------------------------------------------------
  HttpApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: !Sub "users-api-${Stage}"
      ProtocolType: HTTP

  HttpApiStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref HttpApi
      StageName: '$default'
      AutoDeploy: true

  # ----------------------------------------------------
  # 2. ROLES IAM INDEPENDIENTES (Solo logs básicos)
  # ----------------------------------------------------
  GetUsersExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  CreateUserExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  UpdateUserExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  DeleteUserExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  # ----------------------------------------------------
  # 3. FUNCIONES LAMBDA
  # ----------------------------------------------------
  GetUsersFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "users-api-java-${Stage}-getUsers"
      Handler: com.pragma.handler.HandlerGet
      Runtime: java21
      MemorySize: 512
      Timeout: 15
      Role: !GetAtt GetUsersExecutionRole.Arn
      Code:
        S3Bucket: users-api-java-jar
        S3Key: users-api-java-1.1.0.jar

  CreateUserFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "users-api-java-${Stage}-createUser"
      Handler: com.pragma.handler.HandlerCreate
      Runtime: java21
      MemorySize: 512
      Timeout: 15
      Role: !GetAtt CreateUserExecutionRole.Arn
      Code:
        S3Bucket: users-api-java-jar
        S3Key: users-api-java-1.1.0.jar

  UpdateUserFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "users-api-java-${Stage}-updateUser"
      Handler: com.pragma.handler.HandlerUpdate
      Runtime: java21
      MemorySize: 512
      Timeout: 15
      Role: !GetAtt UpdateUserExecutionRole.Arn
      Code:
        S3Bucket: users-api-java-jar
        S3Key: users-api-java-1.1.0.jar

  DeleteUserFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "users-api-java-${Stage}-deleteUser"
      Handler: com.pragma.handler.HandlerDelete
      Runtime: java21
      MemorySize: 512
      Timeout: 15
      Role: !GetAtt DeleteUserExecutionRole.Arn
      Code:
        S3Bucket: users-api-java-jar
        S3Key: users-api-java-1.1.0.jar

  # ----------------------------------------------------
  # 4. INTEGRACIONES Y RUTAS DE API GATEWAY
  # ----------------------------------------------------
  GetUsersIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref HttpApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !GetAtt GetUsersFunction.Arn
      PayloadFormatVersion: '2.0'

  GetUsersRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: 'GET /user/list'
      Target: !Join [ '/', [ 'integrations', !Ref GetUsersIntegration ] ]

  GetUsersLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref GetUsersFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${HttpApi}/*/*/user/list"

  CreateUserIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref HttpApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !GetAtt CreateUserFunction.Arn
      PayloadFormatVersion: '2.0'

  CreateUserRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: 'POST /user/create'
      Target: !Join [ '/', [ 'integrations', !Ref CreateUserIntegration ] ]

  CreateUserLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref CreateUserFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${HttpApi}/*/*/user/create"

  UpdateUserIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref HttpApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !GetAtt UpdateUserFunction.Arn
      PayloadFormatVersion: '2.0'

  UpdateUserRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: 'PUT /user/{id}'
      Target: !Join [ '/', [ 'integrations', !Ref UpdateUserIntegration ] ]

  UpdateUserLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref UpdateUserFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${HttpApi}/*/*/user/*"

  DeleteUserIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref HttpApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !GetAtt DeleteUserFunction.Arn
      PayloadFormatVersion: '2.0'

  DeleteUserRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: 'DELETE /user/{id}'
      Target: !Join [ '/', [ 'integrations', !Ref DeleteUserIntegration ] ]

  DeleteUserLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref DeleteUserFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${HttpApi}/*/*/user/*"